In [9]:
#1.1安装
from __future__ import print_function
import torch
#初始化一个5行3列的矩阵
#自认为后续可用于初始化赋值卷积神经网络参数
x = torch.rand(5,3)
print(x)
torch.cuda.is_available()

tensor([[0.6399, 0.7916, 0.5344],
        [0.3832, 0.4349, 0.8627],
        [0.7099, 0.2541, 0.1896],
        [0.1240, 0.6529, 0.8951],
        [0.9579, 0.0974, 0.8235]])


True

In [3]:
#1.2张量(tensors)
#tensor和多维数组的区别是tensors可以应用到GPU上加快计算速度（这句话还需要很长时间慢慢理解了）
#以下每个创建出来的矩阵都其实是一个tensor

from __future__ import print_function
import torch

#创建一个5x3的矩阵,这个代码是声明一个未初始化的矩阵，相当于C++中的未memset的？
x = torch.empty(5,3)
print("empty_x:",x)

#创建一个随机初始化的5*3矩阵
rand_x = torch.rand(5,3)
print("rand_x:",rand_x)

#创建一个数值都是0，但是类型为long的矩阵
zero_x = torch.zeros(5,3,dtype = torch.long)
print("zero_x",zero_x)

one_x = torch.ones(5,3,dtype = torch.int32)
print("one_x",one_x)

#直接传递tensor数值来创建tensor
#tensor数值是[5.5,3]
tensor1 = torch.tensor([5.5,3])
print("tensor1:",tensor1)

empty_x: tensor([[5.1865e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])
rand_x: tensor([[0.8637, 0.3938, 0.1560],
        [0.6182, 0.7886, 0.4370],
        [0.6442, 0.8876, 0.0139],
        [0.3020, 0.9182, 0.1164],
        [0.4470, 0.1056, 0.8494]])
zero_x tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
one_x tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor1: tensor([5.5000, 3.0000])


In [4]:
#除了上述几种方法，还可以根据已有的tensor变量创建新的tensor变量。
#这种做法的好处是可以保留已有tensor的一些属性，包括尺寸大小，数值属性，除非是重新定义这些属性

#显示定义新的尺寸是5*3，数值类型是torch.double
#稍微有点不明白这种定义方式有什么新奇的
tensor2 = tensor1.new_ones(5,3,dtype = torch.double)
print(tensor2)

#保留相同的尺寸大小
#修改数值类型
#尺寸大小没有改变，但是输出类型改变了。
tensor3 = torch.randn_like(tensor2,dtype = torch.float)
print("tensor3:",tensor3)

#最后对tensor的尺寸获取可以采用tensor.size()方法
print("tensor3.size() = ",tensor3.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor3: tensor([[-0.0669, -0.7156, -0.0420],
        [-1.1982,  2.4167,  0.3713],
        [ 0.1110,  2.4673, -1.3404],
        [-0.9680, -1.8274,  0.9588],
        [-1.0530, -0.2329,  1.0503]])
tensor3.size() =  torch.Size([5, 3])


In [15]:
#1.2.2操作（Operations）
#这里展示了多种加法操作的实现
tensor4 = torch.rand(5,3)
print("tensor3 + tensor4 = ",tensor3+tensor4)
print("tensor3 + tensor4 = ",torch.add(tensor3,tensor4))
#新声明一个tensor变量保存加法操作的结果
result = torch.empty(5,3)
torch.add(tensor3,tensor4,out = result)
print("add result = ",result)
#直接修改变量
tensor3.add_(tensor4)
print("tensor3 = ",tensor3)

#这里引出，可以改变tensor的变量的操作结尾都带有一个'_'

#使用索引访问tensor中某一维的数据
print(tensor3[:,0])#0列
print(tensor3[0,:])#0行

#对tensor的尺寸修改，可以采用torch.view()表示，如下所示
x = torch.randn(4,4)
y = x.view(16)
# -1 表示除给定维度外其余维度的乘积
z = x.view(-1,8)
print(x.size(),y.size(),z.size())
#print("x",x)
#print("y",y)
#print("z",z)


tensor3 + tensor4 =  tensor([[4.3121, 4.3362, 3.9851],
        [3.0356, 7.4158, 7.3409],
        [5.5801, 7.0722, 1.5657],
        [5.3361, 4.2390, 3.9050],
        [3.5736, 6.0294, 7.6059]])
tensor3 + tensor4 =  tensor([[4.3121, 4.3362, 3.9851],
        [3.0356, 7.4158, 7.3409],
        [5.5801, 7.0722, 1.5657],
        [5.3361, 4.2390, 3.9050],
        [3.5736, 6.0294, 7.6059]])
add result =  tensor([[4.3121, 4.3362, 3.9851],
        [3.0356, 7.4158, 7.3409],
        [5.5801, 7.0722, 1.5657],
        [5.3361, 4.2390, 3.9050],
        [3.5736, 6.0294, 7.6059]])
tensor3 =  tensor([[4.3121, 4.3362, 3.9851],
        [3.0356, 7.4158, 7.3409],
        [5.5801, 7.0722, 1.5657],
        [5.3361, 4.2390, 3.9050],
        [3.5736, 6.0294, 7.6059]])
tensor([4.3121, 3.0356, 5.5801, 5.3361, 3.5736])
tensor([4.3121, 4.3362, 3.9851])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
x tensor([[-0.8710, -1.5972,  0.3462,  0.8298],
        [-1.0733, -0.9744,  0.8770, -0.9149],
        [ 0.5426, 

In [17]:
#如果tensor只有一个元素，可以采用.item()来获取类似Python中整数类型的数值：
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1221])
-1.1221100091934204


In [19]:
#1.3和numpy数组的转换
#tensor和numpy数组可以相互转换，并且两者转换之后构想在CPU下的内存空间，改变其中一个另外一个也会改变

#1.3.1tensor转化为numpy数组
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

#以下输出证明两者共享内存空间
a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
#1.3.2numpy数组转换为tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a)
print(a)
print(b)
#在CPU上，除了CharTensor外所有的Tensor类型变量，都支持和Numpy数组的相互转换操作

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
#1.4 CUDA张量
#tensor可以通过.to的方法转换到不同设备上，即CPU或者GPU上，例子如下所示

#当cuda可用的是，可用运行下方这段代码，采用torch.device()方法来改变tensors是否在GPU上进行计算操作

if torch.cuda.is_available():
  device = torch.device("cuda")#定义一个CUDA设备对象
  y = torch.ones_like(x,device = device) #显示创建在GPU上的一个tensor
  x = x.to(device) #也可以采用 to.("cuda")
  z = x+y
  print(z)#两个cuda类型的加在一起了
  print(z.to("cpu",torch.double))#可以改变数值类型


tensor([-0.1221], device='cuda:0')
tensor([-0.1221], dtype=torch.float64)
